### PR TITLE
Fix #15, failing assert when reading large zip files

### LINKED ISSUE #15: Assert failing in zip file with a large number of files
Reading a large file with a huge amount of smaller files inside, it fails:

```
    Assert_failure zip.ml:217:4

    assert((cd_bound = (LargeFile.pos_in ic)) &&
           (cd_entries = 65535 || !entrycnt = cd_entries));
```

Adding debug dump, I see that the entrycnt is not the same as cd_entries, with a hint that in this case cd_entries are truncated, and are not #ffff, but !entrycnt & 0xffff:

cdbound=34a57695, lpos=34a57695, cd_entries=284c, entrycnt=1284c

Suggested fix:
```
zip.ml
     assert((cd_bound = (LargeFile.pos_in ic)) &&
-           (cd_entries = 65535 || !entrycnt = cd_entries));
+           (cd_entries = 65535 || cd_entries = !entrycnt land 0xffff || !entrycnt = cd_entries));
```

### PR DESCRIPTION
**Pull request by einars**

### CODE REVIEW

File: zip.ml [hunk 1]
```diff
@@ -210,7 +210,7 @@ let read_cd filename ic cd_entries cd_offset cd_bound =
            } :: !e
     done;
     assert((cd_bound = (LargeFile.pos_in ic)) &&
-           (cd_entries = 65535 || !entrycnt = cd_entries));
+           (cd_entries = 65535 || cd_entries = !entrycnt land 0xffff || !entrycnt = cd_entries));
     List.rev !e
```
Comment (xavierleroy) [inline zip.ml:214]: It seems that `cd_entries` is always between 0 and 0xFFFF, because it's represented by 2 bytes in the ZIP file.  So, the old `!entrycnt = cd_entries` test is redundant with the new test, `cd_entries = !entrycnt land 0xffff`.  It doesn't hurt either.

**Review by xavierleroy — COMMENTED** [review]
Thanks a lot for the investigation and the fix.  Looks good to me.  There's one test that you could perhaps simplify, see below.  Let me know what you think.

File: zip.ml (hunk 1 above)
Comment (einars) [reply zip.ml:214]: Yep, you're correct.

**Review by xavierleroy — APPROVED** [review]
Sorry I left this PR hanging.  Looks good to me.  Thanks for the code.  Will merge soon.
